[package]
name = "legion-rust"
version = "0.1.0"
authors = ["octaltree <octaltree@gmail.com>"]

[dependencies]
time = "0.1"
rust-crypto = "^0.2"
serde_json = "1.0"

[[bin]]
name = "legion-rust"
doc = false
