[package]
name = "legion"
version = "0.1.0"
authors = ["octaltree <octaltree@gmail.com>"]

[dependencies]
time = "0.1"
rust-crypto = "^0.2"
serde = "1.0"
serde_derive = "1.0"
#serde_json = "1.0"
getopts = "0.2.4"
crust = "0.26.0"
iron = "*"
